/* Automatically generated by liradef toolchain. DO NOT EDIT DIRECTLY. */
#pragma once

#ifndef LIRA_MESSAGE_DEFINITION_H
#define LIRA_MESSAGE_DEFINITION_H

#include <stdint.h>

#define LIRA_MAX_MESSAGE_ID 256

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    LIRA_MSG_ID_HEARTBEAT   = 1,
    LIRA_MSG_ID_GPS_RAW_INT = 33,
} lira_message_id_t;

#ifdef __cplusplus
}
#endif

#endif /* LIRA_MESSAGE_DEFINITION_H */