/* Automatically generated by liradef toolchain. DO NOT EDIT DIRECTLY. */
#pragma once

#ifndef LIRA_MESSAGE_SET_H
#define LIRA_MESSAGE_SET_H

#include <stdint.h>
#include "msgid/msg_definition.h"
#include "msgid/heartbeat.h"
#include "msgid/gps_raw_int.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Helper utility to look up expected payload lengths dynamically by message ID
 * @return expected payload size in bytes, or 0xFFFF if unknown
 */
static inline uint16_t lira_get_message_length(uint32_t msgid) {
    switch (msgid) {
        case LIRA_MSG_ID_HEARTBEAT:
            return LIRA_MSG_LEN_HEARTBEAT;
        case LIRA_MSG_ID_GPS_RAW_INT:
            return LIRA_MSG_LEN_GPS_RAW_INT;
        default:
            return 0xFFFF;
    }
}

#ifdef __cplusplus
}
#endif

#endif /* LIRA_MESSAGE_SET_H */