#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// Import general universal C frame wrapper
#include <liradef/frame/msg.h>
#include <liradef/frame/msg_parser.h>

// Import global enum lookup map
#include <liradef/msgid/msg_definition.h>
#include <liradef/msgid/msg_set.h>

// Import individual packing schemas generated by your python tool
#include <liradef/msgid/heartbeat.h>
#include <liradef/msgid/gps_raw_int.h>

#ifdef __cplusplus
}
#endif
